### ISSUE TITLE
Line Numbers Missing

### ISSUE THREAD

**Issue by tatiana-perry** [trilbymedia/grav-plugin-prism-highlight#1]
I added the class line-numbers to my shortcode and the line numbers do not appear. 

```
[prism classes="language-php line-numbers" highlight="2,4"] 
        <?php
        namespace Grav\Plugin;
        
        use \Grav\Common\Plugin;
        use \Grav\Common\Grav;
        use \Grav\Common\Page\Page;
        
        class PrismHighlightPlugin extends Plugin
        {
            /**
            * @return array
            */
            public static function getSubscribedEvents()
            {
                return [
                    'onPageInitialized' => ['onPageInitialized', 0],
                    'onShortcodeHandlers' => ['onShortcodeHandlers', 0],
                    'onTwigTemplatePaths' => ['onTwigTemplatePaths', 0],
                ];
            }
        }
[/prism]
```

<img width="983" alt="Screen Shot 2019-05-14 at 3 00 14 PM" src="https://user-images.githubusercontent.com/16635677/57728216-0041f400-7659-11e9-8b11-e3090a541bb7.png">

```
enabled: true
theme: prism-base16-ocean.dark.css
all-pre-blocks: true
plugins:
    line-numbers: true
    command-line: false
    command-line-prompt: '$'
```

**Comment by rhukster** [comment]
It might be related to the combination of your indented code, and the use of `all-pre-blocks: true`.

Try removing that indented code as that could conflict with the shortcode (indented code converts to pre in markdown).  Also if that make no diff, set `all-pre-blocks: false`, see if that makes a difference.

**Comment by tatiana-perry** [comment]
I removed ` all-pre-blocks: false` and unindented my code.
The line numbers are still not showing. 

prism-highlight.yaml
``` 
enabled: true
theme: prism-base16-ocean.light.css
plugins:
    line-numbers: true
    command-line: false
    command-line-prompt: '$'
```

```
title: API
taxonomy:
    tag: [article]
related_pages:
    - /tutorials
    - /reference
plugins:
    line-numbers: true
---

# API Page


[prism classes="language-php line-numbers" highlight="2,4"] 
<?php
namespace Grav\Plugin;

use \Grav\Common\Plugin;
use \Grav\Common\Grav;
use \Grav\Common\Page\Page;

class PrismHighlightPlugin extends Plugin
{
/**
* @return array
*/
public static function getSubscribedEvents()
{
return [
'onPageInitialized' => ['onPageInitialized', 0],
'onShortcodeHandlers' => ['onShortcodeHandlers', 0],
'onTwigTemplatePaths' => ['onTwigTemplatePaths', 0],
];
}
}
[/prism]
```
Example of generated HTML after changes:

![Screen Shot 2019-05-14 at 3 56 27 PM](https://user-images.githubusercontent.com/16635677/57731712-ea383180-7660-11e9-9f97-d7f18dc93ec2.png)
